Tarefinha de C...
ThundeRatz/Bixos-2017 pull request #6
Opened 2017-04-26 02:00 UTC by vhenrique21

2017-04-26 02:25 UTC, erickotsuka requested changes
A lógica está certa, só tem o probleminha que citei no comentário. A estratégia está bem simples, mas o intuito dessa tarefa é apenas se acostumar com programação em C voltada para robôs. Estratégias mais elaboradas terá a oportunidade de pensar em breve.

2017-04-26 02:25 UTC, erickotsuka commented on C/Tarefa/main.c
> +		if (sensorFE > 0 || sensorFD > 0) {
Talvez não seja muito claro para você, já que provavelmente você nunca tenha trabalhado com sensores. Os sensores não são perfeitos. Então, o valor mínimo para poder considerar que está vendo o robô será bem maior que zero, provavelmente. Por exemplo, o sensor pode estar retornando um valor de 50 mesmo que o robô não esteja no "campo de visão"do sensor, e é muito provável que aconteça isso. No caso, os valores dos sensores será maior que zero praticamente 100% do tempo de funcionamento.
O valor mínimo que cada sensor precisa para podermos confiar que realmente o robô está perto é definido com testes. E os sensores não são exatamente iguais, logo, é normal que esse valor mínimo seja diferente para cada sensor.
Considerando isso, costuma-se deixar esses valores mínimos de uma forma fácil de mudar todas as ocorrências desses valores (pense um pouco nas coisas de C e tente descobrir uma forma boa de fazer isso. Em caso de dúvida, pergunte).

2017-04-28 19:06 UTC, vhenrique21 reviewed
mudei algumas coisas, não sei se arrumou o problema...

2017-04-28 19:43 UTC, erickotsuka commented
Agora parece certo. Só ir testar e definir essas constantes (pode ser que precise definir uma constante para cada sensor).

2018-03-16 20:00 UTC, closed without merging